# Generated by Django 4.1 on 2022-09-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0002_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='url',
            name='token',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
