# Generated by Django 4.1 on 2022-09-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0004_guest_alter_url_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='urls',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
